publisher_forward_velocity_controller:
  ros__parameters:

    controller_name: "forward_velocity_controller"
    wait_sec_between_publish: 5

    goal_names: ["pos1", "pos2", "pos3"]
    pos1: 
      positions: [0.0, 0.0, 0.0, 0.0, 0.0, 0.05]
    pos2: 
      positions: [0.0, 0.0, 0.0, 0.0, 0.0, -0.05]
    pos3: 
      positions: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
